nelmio_api_doc:
    documentation:
        info:
            title: My App
            description: This is an awesome app!
            version: 1.0.0
        components:
            schemas:
                Customer:
                    type: object
                    properties:
                        id:
                            type: integer
                            description: 'ID du client'
                        last_name:
                            type: string
                            description: 'Nom du client'
                        first_name:
                            type: string
                            description: 'Prénom du client'
                        email:
                            type: string
                            format: email
                            description: 'Email du client'
                        phone:
                            type: string
                            description: 'Téléphone du client'
                        adress:
                            type: string
                            description: 'Adresse du client'
                        registerDate:
                            type: string
                            format: date-time
                            description: 'Date d''inscription du client'
                Seller:
                    type: object
                    properties:
                        id:
                            type: integer
                            description: 'ID du vendeur'
                        name:
                            type: string
                            description: 'Nom du vendeur'
                        prenom:
                            type: string
                            description: 'Prénom du vendeur'
                        email:
                            type: string
                            format: email
                            description: 'Email du vendeur'
                        telephone:
                            type: string
                            description: 'Téléphone du vendeur'
                        dateEmbauche:
                            type: string
                            format: date-time
                            description: 'Date d''embauche du vendeur'
                Option:
                    type: object
                    properties:
                        id:
                            type: interger
                            description: 'ID de l''option'
                        name:
                            type: string
                            description: 'Nom de l''option'
                Reparation:
                    type: object
                    properties: 
                        id:
                            type: interger
                            description: 'ID de la réparation'
                        description:
                            type: string
                            description: 'Description de la réparation'
                        repair_date:
                            type: string
                            format: date-time
                            description: 'Date de la réparation'
                        cost:
                            type: float
                            description: 'Coût de la réparation'
                Sale:
                    type: object
                    properties:
                        id:
                            type: interger
                            description: 'ID de la vente'
                        saleDate:
                            type: string
                            format: date-time
                            description: 'Date de la vente'
                        salePrice:
                            type: float
                            description: 'Prix de la vente'
                        
    
    areas:
        default:
            path_patterns:
                - ^/api/
